version: "3.9"
services:
  app:
    build:
      context: .
    container_name: django-app
    ports:
      - "8000:8000"
    entrypoint: sh /tmp/entrypoint.sh
    volumes:
      - ./tree_menu:/app
    env_file:
      - ./.env
    networks:
      - default

networks:
  default: